### ISSUE TITLE
Home Page has English links in URL

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator.KO-KR#1]
There may be now KO localized-URLs to refer to, however it was noted in a QA that these links connect to English-language pages:

![image](https://user-images.githubusercontent.com/49700217/231267925-19ee70c1-265b-455f-b326-49bca1547528.png)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
Have queried this with the WWL PM

**Comment by stonezy123** [comment]
This is should not be translation, because this is by-design.
https://github.com/MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure.zh-cn/issues/24
